package org.shiwei.handler;



import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RequestMapping;




@Controller
@RequestMapping("SecondMVC")
public class SecondSpringMVCHandler {
	
	
	//算数异常
	@RequestMapping("One")
	public  String testExceptionHandler() {
//		try {
			System.out.println(1/0);  //ArithmeticException： 算数异常
	/*	} catch (Exception e) {
			// TODO: handle exception
		}*/
		
		return "success";
		
	}
	
	
	
	// 数组 越界 异常
	@RequestMapping("three")
	public  String testExceptionHandler2() {
        int[] nems =  new int[2];
        System.out.println(nems[2]);
		return "success";
		
	}
	
	
	// 该方法 可以捕获 本类中 抛出的  ArithmeticException 异常
	@ExceptionHandler({ArithmeticException.class,ArrayIndexOutOfBoundsException.class})
	public String handlerArithmeticException(ArithmeticException e) {
		System.out.println("我捕获了=" + e);
		/*map.put("e", e);*/
		return "error";
	}
	
	
	
	
	

}
